feat(IA): add first IA
m3stash/Anatema_v2 pull request #1
Opened 2020-12-22 21:12 UTC by m3stash

- add abstract class and stateMachine
- add differents aggressivity 
- add first ennemy
- add scriptable configuration
- add patrol management and alert countdown

2020-12-22 22:01 UTC, rvanderaspoilden requested changes

2020-12-22 22:01 UTC, rvanderaspoilden commented on Assets/scripts/IA/States/Fearfull/FearFullAlertState.cs
> +    public override void Update() {
Tu peux enlever ça car ça fera la même chose sans

2020-12-22 22:01 UTC, rvanderaspoilden commented on Assets/scripts/IA/IA.cs
> +        Destroy(currentState);
Pourquoi??

2020-12-22 22:01 UTC, rvanderaspoilden commented on Assets/scripts/IA/IA.cs
> +            endAlertCoroutine = EndAlertCountdown();
C’est pas bon ça, tu ne vas pas récupérer la référence de ta couroutine lancé mais plutôt le contenu d’une coroutine que tu vas lancer. Il faut que tu fasse endAlert = StartCoroutine

2020-12-22 22:01 UTC, rvanderaspoilden commented on Assets/scripts/IA/IA.cs
> +                endAlertCoroutine = null;
Destroy(endAlert) devrait suffire. A vérifier

2021-01-04 20:33 UTC, m3stash commented on Assets/scripts/IA/States/Fearfull/FearFullAlertState.cs
> +    public override void Update() {
done

2021-01-04 20:36 UTC, m3stash commented on Assets/scripts/IA/IA.cs
> +        Destroy(currentState);
je pensais que comme c'était un instantiate contrairement a un new il ne suffisait pas juste d'écraser la référence mais qu'il fallait aussi détruire l'objet unity avant de le re-instantiate.
je l'ai supprimé du coup ^^

2021-01-04 20:46 UTC, m3stash commented on Assets/scripts/IA/IA.cs
> +                endAlertCoroutine = null;
il me dit conversion impossible de UnityEngine.Coroutine en UnityEngine.Object

2021-01-04 20:50 UTC, m3stash commented on Assets/scripts/IA/IA.cs
> +            endAlertCoroutine = EndAlertCountdown();
alors j'ai pas du comprendre mais si je dit que StartCoroutine(endAlertCoroutine) le StopCoroutine(endAlertCoroutine); ne fonctionne plus du coup je me retrouve avec 2 puis 4, 6 couroutine stocké et mon perso commence a aller de plus en plus vite xD

2021-01-04 22:29 UTC, m3stash commented on Assets/scripts/IA/IA.cs
> +            endAlertCoroutine = EndAlertCountdown();
ok je fais ça

2021-01-05 20:30 UTC, m3stash commented on Assets/scripts/IA/IA.cs
> +        Destroy(currentState);
done xD

2021-01-06 19:50 UTC, rvanderaspoilden approved these changes

2021-01-06 20:16 UTC, merged